export const FETCH_MEETUPS_SUCCESS = "FETCH_MEETUPS_SUCCESS";
export const FETCH_MEETUPS_ERROR = "FETCH_MEETUPS_SUCCESS";

export const FETCH_WEATHER_SUCCESS = "FETCH_WATHER_SUCCESS";
export const FETCH_WEATHER_ERROR = "FETCH_WATHER_SUCCESS";

export const INIT_LOADING = "INIT_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const SAVE_MEETUP_SUCCESS = 'SAVE_MEETUP_SUCCESS';
export const SAVE_MEETUP_ERROR = 'SAVE_MEETUP_ERROR';

export const FETCH_BEER_CRATES = "FETCH_BEER_CRATES";

export const UPDATE_MEETUP_ERROR = 'UPDATE_MEETUP_ERROR';

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_ERROR = 'UI SET ERROR';
export const REMOVE_ERROR = 'UI REMOVE ERROR'